
#General settings
[general]
	#A list of buildings that are safe(r)
	excludedBuildings = []
	#List of mobs that can spawn in buildings together with their rarity
	mobs = [".3=minecraft:zombie", ".3=minecraft:spider", ".3=minecraft:skeleton", ".2=minecraft:husk", ".1=minecraft:witch"]
	#List of weapons that the mobs can have together with their rarity
	randomWeapons = [".8=null"]
	#List of helmets that the mobs can have together with their rarity
	randomHelmets = [".8=null", ".2=minecraft:iron_helmet"]
	#List of chestplates that the mobs can have together with their rarity
	randomChestplates = [".8=null", ".2=minecraft:iron_chestplate"]
	#List of leggings that the mobs can have together with their rarity
	randomLeggings = [".8=null", ".2=minecraft:iron_leggings"]
	#List of boots that the mobs can have together with their rarity
	randomBoots = [".8=null", ".2=minecraft:iron_boots"]
	#List of effects that a mob can have. Note that multiple effects are possible
	randomEffects = [".1=minecraft:regeneration,1", ".3=minecraft:fire_resistance,1"]
	#List of console commands to execute the first time a building is entered
	commandFirstTime = []
	#List of console commands to execute every time a building is entered
	commandEntered = []
	#List of console commands to execute when a building is cleared
	commandCleared = []
	#This message is given when the player tries to open a chest in a haunted building
	messageUnsafeBuilding = "§eThe building isn't safe enough!"
	#This message is given when the player enters a haunted building for the first time
	messageBuildingHaunted = "§eThis building is haunted. Be careful!"
	#This message is given when the player clears a building
	messageBuildingCleared = "§aThe building feels a lot safer now!"
	#This message is given when the player is halfway clearing a building
	messageBuildingHalfway = "§eAbout half way there! Keep going!"
	#The amount of ticks that the server waits before checking for new spawns
	#Range: 1 ~ 1000000
	serverTickTimeout = 200
	#The maximum amount of entities that can spawn near each other (of the same type)
	#Range: 1 ~ 200
	spawnMaxNearby = 6
	#The minimum distance between the player and newly spawned mobs
	#Range: 0.0 ~ 16.0
	minSpawnDistance = 8.0
	#The minimum health bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	minHealthBonus = 0.9
	#The maximum health bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	maxHealthBonus = 2.0
	#The minimum damage bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	minDamageBonus = 0.9
	#The maximum damage bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	maxDamageBonus = 1.25
	#The chance that a building is haunted
	#Range: 0.0 ~ 1.0
	hauntedChance = 0.125
	#The minimum amount of mobs that are spawned by a haunted building
	#Range: 1 ~ 10000
	minMobs = 4
	#The maximum amount of mobs that are spawned by a haunted building
	#Range: 1 ~ 10000
	maxMobs = 16
	#The chance that a building is haunted. This version is used in case the building is in a Lost City sphere
	#Range: 0.0 ~ 1.0
	sphereHauntedChance = 0.5
	#The minimum amount of mobs that are spawned by a haunted building. This version is used in case the building is in a Lost City sphere
	#Range: 1 ~ 10000
	sphereMinMobs = 3
	#The maximum amount of mobs that are spawned by a haunted building. This version is used in case the building is in a Lost City sphere
	#Range: 1 ~ 10000
	sphereMaxMobs = 20
	#If this is true then mobs will only spawn if the light level is low enough. Otherwise they spawn regardless of light level
	checkValidSpawn = false
	#If this is true then mobs will only spawn on blocks but not on air
	spawnOnBlock = false
	#If this is true then the player will be notified when a building is cleared
	announceCleared = true
	#If this is true then the player will be notified when he or she enters a haunted building
	announceEnter = true
	#If this is true then the player will get a message when he/she tries to open a locked chest
	announceChestLocked = true
	#If this is true then all chests will be locked until the building is cleared
	lockChestsUntilCleared = false
	#This option is only useful when 'lockChestsUntilCleared'. If true only vanilla chests will be locked. Otherwise all tile entities are locked
	lockOnlyChests = false

